import type { Metadata } from "next";
import Header from "./components/Header/Header";
import "./globals.css";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
  title: "Estate Bode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="bg-white relative overflow-x-hidden">
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
