import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "./components/partials";

export const metadata: Metadata = {
  title: "Estate Bode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="bg-slate-100 relative min-h-screen overflow-x-hidden">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
